### ISSUE TITLE
Request : Make store configurable per cloudtask in MBraceClient.

### ISSUE THREAD

**Issue by krontogiannis** [mbraceproject/MBrace.Core#126]
Add `ICloudValueProvider`,`ICloudAtomProvider`, etc as optional parameters to `MBraceClient.CreateCloudTask`.

**Comment by eiriktsarpalis** [comment]
Or it could take a general `ResourceRegistry` parameter, right?

**Comment by krontogiannis** [comment]
It could, but the users would register `Foo` resources instead of `IFoo`. A general `ResourceRegistry` parameter should be added for non-essential/custom resources.

**Comment by eiriktsarpalis** [comment]
True, but then again depending on the implementation it might be unsafe to specify -say- a user-supplied ICloudValueProvider instance. I think it should be up to the implementer of the runtime to supply overloads of CreateTask that explicitly name what resources can be overridden. Adding a resources parameter would make this work much easier.

**Comment by isaacabraham** [comment]
Yeah - it's currently a little obscure as to how to run against different persistence storage. It would be nice if you could permanently "connect" secondary stores as part of the cluster configuration. Then if you use e.g. CloudValue to get to a file, it would scan all stores for the appropriate container. You could even have a "Data Store" on the configuration which would indicate to the runtime the store to use for data as opposed to everything else.

Obviously some more thought needed around the edge cases here but to me this feels like a "configuration" setting rather than something on a per-request basis.

**Comment by eiriktsarpalis** [comment]
@isaacabraham in principle a global "configuration" setting is doable with the current MBrace.Core. Ad-hoc configuration however is not, which I think in some cases might be useful.

**Comment by isaacabraham** [comment]
Sorry - wasn't clear in my earlier message. I'm referring to the MBraceConfig object you supply when getting a cluster handle.

Of course having the ability to ad-hoc change the store is useful - but having in-built support from an MBraceConfig point of view would be great too.

**Comment by eiriktsarpalis** [comment]
@isaacabraham I think you were, that's what I understood :)

So yes, you can do this but it's really an MBrace.Azure functionality issue, not MBrace.Core related.

**Comment by isaacabraham** [comment]
ah, gotcha :-)
