### ISSUE TITLE
ThespianCluster creates tons of empty json log files

### ISSUE THREAD

**Issue by cotyar** [mbraceproject/MBrace.Core#162]
I'm running a local ThespianCluster from F# interactive and having the temp folder blowing up (Windows 10). Each worker creates tons of empty json log files on name like:

_"logs-20160310T213935259Z.json"_

at more than 1000/min rate in folders like:

_"%PATH%\mbrace-uuid3c64f8b9-3f8c-4b51-a1e4-1ecb76b1535d\systemLogs--29760"._

I tried to change the loglevel for the cluster and using different logger but it doen't have any effect on the problem at all.

Is it my incorrect setup or some kind of an expected behaviour please? 
Many thanks in advance.
Yuriy

**Comment by eiriktsarpalis** [comment]
Hi,

This is expected behaviour. This is testing a cloud logging implementation in which new log entries are appended as files in a cloud storage service, which we assume to be immutable. I just pushed commit 6b60ffcb6e99ea8bb92f977f64ff96a95ffb756f which tweaks granularity of generated json files, as well as exposing persist interval configurations for thespian workers. Note that setting this too high may affect latency in which logs appear in the client side.

**Comment by eiriktsarpalis** [comment]
By the way, are the files you're seeing literally empty or do they simply contain too few entries?

**Comment by cotyar** [comment]
Many thanks Eirik for a very quick reply and the fix of course.

All of them I've seen were empty. But I'll give it another go find the
answer as soon as get back to my machine.

Thanks again

Yuriy

**Comment by cotyar** [comment]
All of them are empty

**Comment by cotyar** [comment]
Looks solved.

Great thanks Eirik!

**Comment by isaacabraham** [comment]
Check me out, giving a comment a thumbs up!
