### ISSUE TITLE
Suggest Distributed.map --> Array.mapCloud?

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Core#18]
See my comment here https://github.com/elastacloud/mbrace-on-brisk-starter/commit/b49dc4cf358e6687b39d76b0e69a4cc09750de9d#commitcomment-10005315

I suggest considering the following renamings for the Distributed module

    Distributed.map  --> Array.mapCloud
    Distributed.choose  --> Array.chooseCloud

etc.  Perhaps also with "List" variations? Also is taking a "sequence" as input risky since sequence values are not necessarily serializable?

**Comment by eiriktsarpalis** [comment]
The [Distributed](https://github.com/mbraceproject/MBrace.Core/blob/master/src/MBrace.Core/Workflows/Distributed.fs#L59) naming was chosen because there also exists a [Sequential](https://github.com/mbraceproject/MBrace.Core/blob/master/src/MBrace.Core/Workflows/Sequential.fs#L18) module in the same namespace. These contain more or less the same set of combinators but with different execution semantics. Since MBrace allows you to define the same combinators in many but subtly different ways, my thinking here was that these differences should be disambiguated by grouping combinator families under modules with distinctive names.

Using sequence as input is not really a problem w.r.t. serialization since in the former case it is converted to array before being partitioned among the worker machines and in the latter it never escapes the local execution context.

**Comment by dsyme** [comment]
Ah, ok, I see.....   The naming of the collection of combinator functionality in Cloud.Parallel, Distributed.* and Sequential.* definitely needs real care.  There are hugely important operational distinctions and user-guidance-about-what-kind-of-parallelism-to-use being introduced there.  

For example, ``Sequential`` (which I just looked at) wasn't at all what I thought it was - I thought it was somehow going to be local, sequential execution on a single thread on a single machine, when it's actually sequential/iterated composition of ``Cloud<T>`` computations.  The name ``Sequential.map`` really doesn't capture that there's anything related to the cloud at all.

My initial intuition is that it's not right to make such a major operational distinction by module name.  

Some notes to myself

* "Distributed" = distributed-then-multi-core-divide-and-conquer-combinators
* "Sequential" = sequential/iterated composition of ``Cloud<T>`` computations

TBH we've never really addressed some of these naming questions in F#.  For Async, we don't have an ``List.mapAsync`` (though c.f. ``AsyncSeq.mapAsync``) or ``Async.mapList`` or the like.  In general we de-emphasize combinator programming over Async values beyond Async.Parallel and a few others - not because it's a bad idea, but more because it raises the level of competence the F# programmer needs, and can be subtle.

We do have ``Array.Parallel.map`` which gives one naming precedent.  But we just accept that one input type, and don't do ``List.Parallel.map`` etc.

**Comment by eiriktsarpalis** [comment]
The module names are of course provisional. These should be updated and better documented as we add more families of combinators. For instance, a different 'Distributed' collection could simply pass all inputs to `Cloud.Parallel`, without worker core capacity being taken into account.

Regarding the `Sequential` combinators, these are in fact intended for sequential in-process computation. They will most likely fail if passed workflows that introduce distribution since some of them freely make use of potentially non-serializable state. This issue is [elegantly addressed](https://github.com/mbraceproject/MBrace.Core/blob/local-workflows/src/MBrace.Core/Workflows/Sequential.fs#L101) in the `local-workflows` branch. That said, it would make sense to offer a different flavour of 'sequential' combinators that actually compose with distributable computations. This would be a common requirement when implementing iterative algorithms, for example.

BTW, I should probably mention that these and [other](https://github.com/mbraceproject/MBrace.Core/blob/local-workflows/src/MBrace.Core/Workflows/Common.fs) [workflows](https://github.com/mbraceproject/MBrace.Core/blob/local-workflows/src/MBrace.Core/Store/CloudSequence.fs) are 'library' code, i.e. implementations that live on top of the programming model. We used to keep a separate assembly for these types of things but in the end opted for a more monolithic, FSharp.Core-like approach.

**Comment by dsyme** [comment]
I suggest the following naming:

    Cloud.divideAndMap
    Cloud.divideAndTryFind
    ...
    Local.map
    Local.tryFind
    ... 

For the first two possible even go as far as this:
 
    Cloud.divideAndLocalMap
    Cloud.divideAndLocalTryFind

Either way this avoids adding the two top-level adjectives ``Distributed`` and ``Sequential`` which are awkward - instead it reuses existing matching concepts in a fairly reasonable way. It does of course prejudice the ``Cloud.*`` and ``Local.*`` API to assume a collection as input (so Local.map is not of type ``(T -> U) -> Local<T> -> Local<U>`` but rather ``(T -> Local<U>) -> seq<T> -> Local<U[]>`` but I think that is OK.

I suggest the longer names like ``divideAndMap`` (or ``divideAndLocalMap``) because the divide-and-conquer-assuming-work-is-balanced heuristic used in the first two (currently called ``Disributed.*``) really needs to be called out in the name, and you want to do this in a way that leaves room for later alternative heuristics.  The simple name ``map`` doesn't convey what's happening - people assume a ``map`` is "uniform" in some sense.   

(Note that in very many situations the work of a map will not be evenly balanced, and there is plenty of reason to expect to add either optional arguments or further functions which specify how work is best to be divided.)

**Comment by eiriktsarpalis** [comment]
Yes, I see your point. But will this not result in the `Cloud.*` space being polluted w.r.t. intellisense? It could contain:
```
...
Cloud.divideAndLocalMap
Cloud.divideAndLocalFilter
Cloud.parMap
Cloud.parFilter
Cloud.sequentialMap
Cloud.sequentialFilter
...
```
Unless these are to be tucked inside discrete namespaces, I think that the top-level distinction is more readable:
```
DivideAndLocal.map
DivideAndLocal.filter
Parallel.map
Parallel.filter
Sequential.map
Sequential.filter
```
Perhaps these things should be placed in a separate library, to allow a more organic development by the user community, à la FSharpx.

**Comment by dsyme** [comment]
Hmmm... I don't think I'd recommend having the words distinguishing the operational behaviour of the operators in the module name (DivdeAndLocal etc.).   First, such modules/types are costly in the overall API complexity budget - and minimizing the number of modules and type names in the API design is really important.

Second, the precedent for putting the operational behaviour in the module name in FSharp.Core is ``Array.Parallel.map`` etc. But that still has ``Array`` and I really think that should have been ``Array.parallelMap`` etc.  anyway

I also agree that in some cases it may be best to just leave these as a separate library or sample, until you're sure that it's the right abstraction and the abstraction is fundamental to MBrace.  For `Sequential.*`` the code for these is really simple and instructive anyway - it is easier to read the implementation and adapt it yourself than actually learn the operators.  I'm not sure it's worth having them in the design at this stage.

For ``Distributed.*`` it's trickier.  They are useful but a little awkward to teach. For example, when would you recommend a ``divide and local`` over CloudStream(CloudFlow) programming?   Perhaps it's best just to concentrate on ``cloud { ...}`` and CloudStream programming as the primary models the user needs to know?

**Comment by eiriktsarpalis** [comment]
The workflow offered by the `Distributed.*` combinators is very similar to `CloudStream`. The former has applications more general than streams but does not offer composability as CloudStream does. It is better suited when doing things like IO-bound computation or when hand-writing reduction code in stream-like scenaria is necessary. 

I suppose that such combinators cannot be used effectively unless the underlying workflow is fully understood by their consumers, so they probably should be placed separately in a community library in a way that source code can be easily accessed and evaluated. That said, I think that their existence in the core library is highly convenient, thus avoiding having to write an ad-hoc implementation of `tryFind` for example.

**Comment by eiriktsarpalis** [comment]
I'm just going to quote @isaacabraham from a similar issue
>The starter pack demos are a great way to get up and running.
>
>However! There are currently a number of top-level modules for computations that do similar (or the >same) thing (albeit perhaps with different behaviour / performance characteristics). A good example of >this is Cloud.Parallel and DivideAndConquer.Map. The former takes a Cloud 'R array and executes it in >parallel. A common pattern is to go from 'T Array to Cloud 'R Array vai Array.map and then >Cloud.Parallel. The latter takes a collection of 'T and a 'T -> Cloud 'R and executes it in parallel.
>
>The standard pattern seems to be to use Cloud.Parallel. Why have two? The latter seems to be a more >efficient way of doing things as it bundles up jobs into single jobs etc. which is a good thing. But then >you end up with two modules doing similar things.
>
>I would suggest that at some point before 1.0, a review should be made of the common tasks etc. >involving cloud computations; these could be put together into a top-level module in a very basic >manner - just the 80% of things that the beginner and average user will want to see, in order to increase >the pit of success and reduce going down blind alleys or leading to initial confusion. The remaining >should be put into a set of sub-namespaces e.g. .Advanced. or similar.

**Comment by eiriktsarpalis** [comment]
The problem with `DivideAndConquer.map` is that it only works given certain assumptions: workload is uniform across inputs; computation is CPU bound since chunking is done according to core capacity; the mapper function is single-threaded. While a convenient combinator to have, I try not to attach too much importance to it. 

In practice, every problem has peculiarities that require a variation of implementation. For instance I wrote [this](https://github.com/mbraceproject/demo-digit-recognizer/blob/master/src/DigitRecognizer/utils.fs#L94) for the knn example.

Given the difficulties of distributed computation, I find it difficult to have a single combinator that offers optimal performance for each conceivable application. At the same time, using a combinator without understanding its underlying workflow will almost certainly result in suboptimal execution. In that respect, I tend to agree with @dsyme, we should probably avoid adding a bunch of obscurely named combinators to the core library. In practice, I think that there will be specialised libraries that consume the `Cloud.Parallel` primitive in an ad-hoc fashion. MBrace.Streams is a good example of this, more will definitely follow.
