### ISSUE TITLE
Discussion thread: naming for CloudSequence and CloudStream

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Core#20]
Hi all,

I'd like to start a discussion thread about the names "CloudSequence" and "CloudStream". Caveat: I haven't delved into CloudSequence much, and have only gone through the basic combinatory programming with CloudStream.

OK, so I guess I'm concerned by the naming here, from the perspective of a newcomer:

- CloudSequence sounds totally like it is "an IEnumerable in the cloud". It's not.

- CloudStream sounds like it is, well, for streaming data.  It's not really, at least not yet.

So both newcomer intuitions are incorrect (I believe).  As I understand it, 

- ``CloudSequence<T>`` is an immutable array of data items of type ``T`` stored in a CloudFile in cloud storage.  It is definitely not an abstract interface-based notion like ``seq<T>``

- ``CloudStream<T>``  is for composing a data-parallel workflow, normally starting with fixed partitioned data and files, streamed through a set of combinators in a DryadLinq-style.

For CloudSequence, why not call it like it is - either ``CloudFile<T>`` (using generic overloading), or ``CloudCollectionFile<T>`` or the like?    Why use the word "sequence" when it has so many other connotations in F#?  I think I'd really recommend a change here.

For CloudStream.... OK, so the horse may have bolted here - since this naming is related to the Stream library from Nessos :)

As background I've always been loathe to "use up" the "Stream" name in F# nomenclature - for starters, the name is used in System.IO, and secondly it was used by an obscure (and little used) OCaml feature, and thirdly it has the streaming-data connotation above.  But I still wonder if a word like "Flow" might serve MBrace users better, and leave open the possibility of using the "stream" word for later, e.g.

``
    arrayOfDataInCloud
    |> CloudFlow.ofCloudVector
    |> CloudFlow.map (Array.sumBy (fun (i,j) -> i+j))
    |> CloudFlow.sortBy (fun n -> n) 10
    |> CloudFlow.toArray
    |> cluster.CreateProcess
``
or
``
    arrayOfDataInCloud
    |> CloudDataFlow.ofCloudVector
    |> CloudDataFlow.map (Array.sumBy (fun (i,j) -> i+j))
    |> CloudDataFlow.sortBy (fun n -> n) 10
    |> CloudDataFlow.toArray
    |> cluster.CreateProcess
``
Equally I can see the Nessos stream library has filled the space I originally left, and with something very good too! :+1:  :)  So I'd understand if you kept this naming!

**Comment by palladin** [comment]
Hi Don,
I completely agree with your arguments about the name of CloudSequence<'T>. Maybe a name like the one you mentioned CloudCollectionFile<T> (emphasis on the File) is a better one. Now, for the CloudStream... I have a very bad experience trying to clear up the confusion around the term "Stream" but on the other hand we have the success of java 8 streams (which is also the source of our inspiration).

**Comment by palladin** [comment]
One technical reason in favour of the name CloudStream is the core dependence of Streams/ParStreams for sequential and local parallelism.

**Comment by krontogiannis** [comment]
* I think Cloud_Sequence_ was introduced as an alternative to CloudRef because we wanted something similar that wouldn't fetch it's entire payload in memory, but would deserialize on demand (thus the 'sequence' part of the name). I feel like a new name for cloudseq should declare it's lazy nature (or else we could just stick with a CloudRef<'T []>).
* I don't know if we are going to move from the 'Streams' term, but the `Flow` term is far better IMO.

**Comment by palladin** [comment]
Maybe CloudSeqFile<'T> (i really like the file part) :)

**Comment by eiriktsarpalis** [comment]
@dsyme I tend to agree with your naming objections, particularly CloudSequence. At some point we were investigating the possibility of a new name, something that would convey the idea that it is a collection of elements which is contained within a *single* file. We rejected CloudCollection since CloudVector is also one and CloudBucket because it implies mutability. Same for CloudArray (NB CloudArray *used* to be the name for what is now CloudVector). We stuck to the original name out of lack of inspiration.

I think @palladin can confirm that the Streams name was taken from the Java 8 library of the same name. I agree though that this is an overloaded term both in the context of .NET and the cloud. Perhaps it should be renamed, but the Nessos.Streams project definitely introduces a certain amount of inertia against such a move. Flow looks like a nice alternative.

I remember you mentioned a few days earlier some criticisms about the naming of CloudRef (though I can't seem to find the particular). Do you think that CloudCell would be an adequate replacement?

**Comment by dsyme** [comment]
How about:

    CloudValue (instead of CloudRef)
    CloudVector
    CloudFile
    CloudValuesFile or CloudCollectionFile or CloudSequenceFile
    CloudAtom

and possibly

    CloudFlow (for CloudStream)

**Comment by eiriktsarpalis** [comment]
I like CloudValue but I'm kind of concerned that its name may not communicate the fact that instances are in fact references. Incidentally, I just came across [this paper](http://infoscience.epfl.ch/record/205822/files/f-p.pdf) which uses the term `Silo[T]/SiloRef[T]`for a similar construct.

How about CloudChunk or CloudPartition instead of CloudSequence?

I should also ask, is it absolutely necessary to maintain the Cloud* prefix for all things MBrace?

**Comment by dsyme** [comment]
The problem with Ref is that it should either be used consistently or not at all, I think you would need

    CloudValueRef (instead of CloudRef)
    CloudVectorRef
    CloudFileRef
    CloudValuesFileRef/CloudCollectionFileRef/CloudSequenceFileRef
    CloudAtomRef

Cloud works for me, it makes me happy to have cloud things distinguished, and the symmetry between ``cloud { ... }``, ``Cloud<T>`` and ``Cloud*`` is very pleasing and seems fundamental to how the programming model will compose nicely with any other kind of non-cloud F# (and C#) programming.

**Comment by dsyme** [comment]
Closing this as it's an old discussion resolved in MBrace 1.0
