### ISSUE TITLE
Best way to create a CloudVector where each item is very large (CloudVector.ofCloudCells or ...?)

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Core#35]
I'm creating a CloudVector of type ``CloudVector<(DateTimeOffset * float) []>`` of overall size 100GB, where each entry is a 1GB time series data. Note I'm expecting to process each particular time series in-memory on a single worker.

I first created data as 100 cloud cells, each containing a ``(DateTimeOffset * float) []`` (1 GB each).  I had somehow expected to find something like this:

    CloudVector.ofCloudCells : seq<CloudCell<T>> -> Local<CloudVector<T>>

I didn't immediately see how to create the CloudVector without having all the data in memory of a single worker at any point in time.  I thought of using ``CloudVector.ofCloudFiles`` but this felt like it would be artificial.

In the end I used 100 instances of ``CloudVector.New [| oneArrayOfData |]`` followed by a ``CloudVector.Merge``.  But it feels like there should be another way to do this.  And CloudVector.OfPartitions felt strangely misleading - from its name I though that's what I needed, but it wasn't.

**Comment by krontogiannis** [comment]
Hmm, yeah this might be an issue.CloudVector is friendly to CloudSequence partitions only (or CloudSequence's created from CloudFiles); CloudSequences are even exposed in CloudVectors instance members. 

But my question is what made you use `CloudCell` instead of `CloudSequence` in the first place? Is it caching or the expectation that the time series should be processed in-memory? (CloudSequence can do both AFAIK). 

I feel like there is a conflict between `CloudCell` and `CloudSequence` in respect with which one should the user choose. Personally i would expect cells to hold medium sized (a few MBs or a few 100s) non- enumerable payload, and cloudseq for anything else. Maybe we should decide why do we need each one of those primitives and communicate better where they should be used.

**Comment by eiriktsarpalis** [comment]
CloudVector is now being renamed to PersistedCloudFlow and is a subtype of CloudFlow - just like Spark. The `PersistedCloudVector.New` APIs etc have been made internal in the `MBrace.Flow` library. It is now only possible to create instances via the `CloudFlow.persist : CloudFlow<'T> -> PersistedCloudFlow<'T>` combinator.
