### ISSUE TITLE
CloudVector on a single large element uses two partitions, one very small

### ISSUE THREAD

**Issue by dsyme** [mbraceproject/MBrace.Core#36]
When you create a cloud vector for one item which logically fits in one partition, you get two partitions, the second of which is very small.

For example:
```
let cv2 = CloudVector.New ([| [| 0 .. 100000 |] |], 100000L) |> cluster.Run

cv2.PartitionCount
[ for p  in 0 .. cv2.PartitionCount - 1 -> cv2.GetPartition(p).Size |> cluster.Run ]
```
gives:

```
val it : int64 list = [400048L; 35L]
```

**Comment by eiriktsarpalis** [comment]
This is because of the partitioning strategy used by CloudVector; new files are created every time a size theshold is reached. CloudVector is now being renamed to PersistedCloudFlow and is a subtype of CloudFlow - just like Spark. The `PersistedCloudVector.New` APIs etc have been made internal in the `MBrace.Flow` library. It is now only possible to create instances via the `CloudFlow.persist : CloudFlow<'T> -> PersistedCloudFlow<'T>` combinator.
