### ISSUE TITLE
Could not load Deedle when running code for second time

### ISSUE THREAD

**Issue by tpetricek** [mbraceproject/MBrace.Core#88]
I wrote an M-Brace demo that uses Deedle - quite curiously, it works fine the first time I run it, but breaks down when I run the code again. The [script is here](https://github.com/tpetricek/Talks/blob/master/2015/scalable-ml-ds-fsharp/code-done/world-scale.fsx) - I can try getting a smaller repro, but I thought I'd share the whole thing first. 

The first part of the code creates `CloudValue<string * Series<string, float>>`. This bit works fine (I was thinking serializing Deedle series might go wrong, but it seems to be working good!)

The next part of the code reads the cloud value and runs K-means clustering on countries (using just a single cloud job). This works fine when I run it once, but when I run the lines 139-141 for the second time, I get the following ([full error message is here](http://pastebin.com/N60iRpiq)):

> System.IO.FileNotFoundException: Could not load file or assembly 'Deedle, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
> File name: 'Deedle, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null' ---> System.IO.FileNotFoundException: Could not load file or assembly 'Deedle, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
> File name: 'Deedle, Version=1.0.7.0, Culture=neutral, PublicKeyToken=null'

This also happens when I try to run multiple things in parallel, for example using:

    let p3 = 
      [ for i in 0 .. 10 -> kmeans distance aggregator 3 cloudWorld ]
      |> Cloud.Parallel
      |> cluster.CreateProcess

Some things I noticed:

 - I wrote this without using Deedle and that worked fine
 - I changed the code so that it does not store Deedle values in `CloudValue`, but that did not help
 - After it starts failing, even simple things like `cloud { return 1 + 1 } |> cluster.Run` stop working (throw the same error). `cluster.Reset()` does not help - and I basically had to recreate the cluster.

Is there something obvious I'm missing? What should I do to get a more useful log for you to look at?

**Comment by eiriktsarpalis** [comment]
Hi Tomas,

I couldn't reproduce the error, but judging from your stacktrace this looks like a Vagabond issue. It is a crash that occurs on the client side when Vagabond is parsing the fsi dynamic assembly. This means that recording how the entire fsi session unfolded, including the sequence of interactions and how they were grouped together is crucial to providing a consistent reproduction. Try adding the following at the beggining of your script:
```fsharp
open MBrace.Azure
cluster.AttachClientLogger(new ConsoleLogger())
```
This will produce log outputs as you submit code to the cloud, for example:
```
30052015 13:12:43.162 +03:00 Creating process a803c252c526472a9e2696b1839106ec 
30052015 13:12:43.162 +03:00 Computing dependencies
30052015 13:12:43.287 +03:00 Uploading dependencies
30052015 13:12:44.489 +03:00 Uploading 'FSI-ASSEMBLY_2f9c4fbf-802d-4088-bde8-9098ee67b264_6, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' [IMG 5.00 KiB]
```
Please record the occurrences of such FSI-ASSEMBLY uploads, including the numerical suffixes at the end of their names, i.e. `_6`.

Having a closer look at your stacktrace, I think that I can trace the problem to the following lines:
```
   at ProviderImplementation.AssemblyResolver.init@138-2.Invoke(Object sender, ResolveEventArgs args) in C:\Git\FSharp.Data SourceLink\src\CommonProviderImplementation\AssemblyResolver.fs:line 138
   at System.AppDomain.OnReflectionOnlyAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
   at Nessos.Vagabond.AssemblyParser.tryRemapReferencedType(DynamicAssemblyCompilerState state, Type t) in 
```
It looks like the `Assembly.GetType()` call causes an assembly resolver registered by `FSharp.Data` to be fired. This is interesting because Vagabond also relies on its own assembly resolver. This could happen due to a bug in Vagabond or FSharp.Data, or simply due to the fact that both logics rely on the same piece of global mutable state. We need a reproduction to be sure.

**Comment by isaacabraham** [comment]
Could this be a version mismatch issue? Brisk is as of last weekend serving up 0.6.8 clusters. Make sure the starter pack or mbrace dependencies on the client side match?

**Comment by eiriktsarpalis** [comment]
@isaacabraham Probably not, this looks unrelated to MBrace and any cluster state. Can't be sure before a reliable repro is available though.

**Comment by tpetricek** [comment]
Thanks for looking into this - I'm using the correct version of M-Brace, but I had an older version of F# Tools on this machine. I updated to the latest F# and it works fine!

**Comment by eiriktsarpalis** [comment]
Interesting. It still has the smell of a bug though, I wouldn't be too surprised if it popped up again.
