### ISSUE TITLE
Programming model documentation issues

### ISSUE THREAD

**Issue by breyed** [mbraceproject/MBrace.Core#89]
Here are some issues with the [programming model doc](http://www.m-brace.net/programming-model.html). (I couldn't find the source to contribute fixes directly.)

#### Section: Parallelism Combinators

Second example ends with `return raise e`. This has two problems:
* `raise` doesn't return
* To re-raise an exception, you should use `reraise`, which better preserves the stack for debugging.

#### Section: Example: Defining a MapReduce workflow
> it does enable data parallelism

missing the word *not*

**Comment by eiriktsarpalis** [comment]
Hi Edward, 

`return raise e` is standard syntax for F# computation expressions. Also, `reraise` will not work in this context since cloud workflows do not correspond to stacks in the traditional sense. This is not MBrace-specific, the same happens when using `async`.

The typo has been fixed and published. You can find the documentation source [https://github.com/mbraceproject/mbrace-docs](here).

**Comment by breyed** [comment]
Thanks for making the fix and for the insight into re-raising exceptions. I haven't used computation expressions much, so the need to use `return raise e` is new to me. Any suggestions on where to learn more about that? And speaking of links, the link to the documentation source didn't work.

**Comment by eiriktsarpalis** [comment]
It's been fixed now.
